language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux

matrix:
  allow_failures:
    - rust: nightly

fast_finish: true
cache: cargo
before_script:
  - touch .env
  - rustup component add clippy

script:
  - cargo test
  - cargo clippy -- -D warnings
